apiVersion: v1
kind: Namespace
metadata:
  name: spin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: spin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "pgdata"
      volumes:
        - name: pgdata
---
apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: webhook-spin-app
  namespace: spin
spec:
  image: "ttl.sh/webhook-spin-app:24h"
  executor: containerd-shim-spin
  replicas: 1
  variables:
    - name: db_user
      value: postgres
    - name: db_name
      value: postgres
    - name: db_host
      value: postgres
    - name: db_password
      value: password
