apiVersion: v1
kind: ConfigMap
metadata:
  name: sql-scripts
  namespace: spin
data:
  create_table.sql: |
    CREATE TABLE transfers
    (
        transfer_id   UUID,
        transfer_date DATE,
        value         INTEGER,
        origin        TEXT,
        status        TEXT
    );
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    service: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    service: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: spin
  labels:
    service: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgres
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - mountPath: "/docker-entrypoint-initdb.d/"
              name: sql-scripts
      volumes:
        - name: sql-scripts
          configMap:
            name: sql-scripts

---
apiVersion: core.spinkube.dev/v1alpha1
kind: SpinApp
metadata:
  name: webhook-spin-app
  namespace: spin
spec:
  image: "ttl.sh/webhook-spin-app:24h"
  executor: containerd-shim-spin
  replicas: 1
  variables:
    - name: db_user
      value: postgres
    - name: db_name
      value: postgres
    - name: db_host
      value: postgres
    - name: db_password
      value: password
